<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link rel="stylesheet" type="text/css" href="/css/homepage.css">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
</head>
<body>
<h1 id="title">Completed</h1>


<div>
    <?php

    foreach ($tasks as $task) {

        echo "<br><form method='get' action='/delete/$task[id]'> $task[name]<input id='deleteBtn' type='submit' value='Delete'></form>";

    }

    ?>
</div>

<div>
    <form action='/'><input id='goHomeBtn' type='submit' value='Go Home'></form>
</div>

</body>
</html>
