<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link rel="stylesheet" type="text/css" href="/css/homepage.css">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
</head>
<body>

<h1 id="title">Up Next</h1>

<div>
    <?php
    $input = $_GET['input'];
    echo "<form action='/add' method='get'>";
        echo "<input id='inputField' type='text' name='newTask' placeholder='new task'>";
        echo "<input id='inputBtn' type='submit' value='Add'>";
    echo "</form>";
    ?>
</div>

<div>
    <?php

    foreach ($tasks as $task) {

        echo "<br><form method='get' action='/mark/$task[id]'> $task[name]<input id='doneBtn' type='submit' value='Done'></form>";
    }

    ?>
</div>

<div>
    <form action='/done'><input id='viewCompletedBtn' type='submit' value='View Completed Tasks'></form>
</div>

</body>
</html>
